;; -*- no-byte-compile: t; -*-
;;; packages.el

(package! emacs-snippets :recipe (:fetcher github :repo "hlissner/emacs-snippets" :files ("*")))
(package! prettify-utils :recipe (:fetcher github :repo "Ilazki/prettify-utils.el" :files ("*")))
(package! pinentry)
(package! helpful)
(package! tldr)
(package! parinfer)
(package! lispy)
(package! lispyville)
(package! company-childframe)
(package! sed-mode)
(package! company)
(package! company-statistics)
(package! company-dict)
(package! ov)
(package! alert)
(package! ess)
(package! shr-tag-pre-highlight)
(package! orgit)
(package! evil-magit)
(package! magithub)
;; (package! evil-string-inflection)
(package! electric-operator)
(package! lsp-mode)
(package! company-lsp)
(package! lsp-ui)

(package! ivy-posframe)
(package! flycheck-posframe)

(package! evil-collection)

(package! academic-phrases)
