#+TITLE: fuxialexander's doom-emacs based Emacs config
I've been quite into Emasc since 2017. Previously I use a spacemacs-based
config, later I found that I'm not the type of person who tend to keep a
long-running Emacs session. I the kind of person who consistently fiddle in the
Emacs rabbit hole. Thus I move my config to use ~doom-emacs~ which gives me
faster startup time and a lean, mean environment for me to play with
~Emacs-lisp~. 
* Good stuff
:PROPERTIES:
:ID:       92E3B456-0358-4557-90F4-4B8A802F033D
:END:
- An integrated literature management system based on ~org-ref~: use org mode
  for PDF annotation, get literature from ~elfeed~, etc. 
- A usable ~notmuch~ email client
- ~org-gcal~ & ~calfw~ based calendar with beautiful theme
- Cool ~twittering.el~ UI mods (have been integrated to ~doom-emacs~)
- Uses as many ~child-frame~ as I can
- A hand-crafted org-html export theme with searchable table, link to ~Skim.app~
  annotation, table of contents, foldable code blocks and clean interface. 
- ~ob-ipython~ and ~org~ based data science notebook with support of remote
  kernel. 
  
* Getting start
:PROPERTIES:
:ID:       D3947C92-6876-4B52-8A8C-98846A2D466E
:END:
Simply clone both ~doom-emacs~ and my config
#+BEGIN_SRC bash
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
cd ~/.emacs.d && git checkout develop
git clone https://github.com/fuxialexander/doom-emacs-private-xfu ~/.doom.d
#+END_SRC

And use ~doom~ to install the packages, etc.
#+BEGIN_SRC bash
export PATH="~/.emacs.d/bin:$PATH" # You can add that to your ~/.*shrc
doom install
#+END_SRC

* To-do list
Here are some stuff that I plan to work on in my spare time:
- [ ] An updated Elfeed UI
  - [ ] Automatically parse the feed to get paper ~DOI~, and fetch the corresponding
    abstract if avaliable (currently some feeds only show title).
  - [ ] Ability to switch between different layout which have different information
    density
  - [ ] Make it beautiful and modern.
- [ ] An ~+dtach~ module which enhances different editing experience with
  multihops TRAMP connection

* TODO 
:LOGBOOK:
- State "TODO"       from              [2018-07-12 Thu 20:17]
:END:
